//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace REST.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KeywordResponseSet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KeywordResponseSet()
        {
            this.Subreddits = new HashSet<Subreddit>();
        }
    
        public int Id { get; set; }
        public int UserId { get; set; }
        public int StatusId { get; set; }
        public string Keyword { get; set; }
        public string Response { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Subreddit> Subreddits { get; set; }
    }
}
