//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace REST.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Subreddit
    {
        public int Id { get; set; }
        public int KeywordResponseSetId { get; set; }
        public string Subreddit1 { get; set; }
    
        public virtual KeywordResponseSet KeywordResponseSet { get; set; }
    }
}
